pipeline:
  frontend:
    image: node:8.1.2
    group: laravel
    commands:
      - node -v
      - npm -v
      - yarn --version
  deploy:
    image: appleboy/drone-ssh
    host: {HOST}
    username: {HOST_USER}
    password: {HOST_PASSWD}
    port: 22
    script:
      - git clone https://github.com/alezzigo/test-mediacustom.git /home/drone/datagit
      - cp /home/drone/datagit/index.html /home/drone/web
      - ls -lah ./web
