pipeline:
  frontend:
    image: node:8.1.2
    group: laravel
    commands:
      - node -v
      - npm -v
      - yarn --version
  deploy:
    image: appleboy/drone-ssh
    host:51.15.208.87
    username:drone
    password:Abc@123456
    port: 22
    script:
      - cd /var/www/html/
      - ls -lah
